"""Diagram standards data — stencils, shapes, edges, and layout conventions for each diagram type."""

STANDARDS: dict[str, dict] = {
    # ═══════════════════════════════════════════════════════════════
    # UML Diagrams
    # ═══════════════════════════════════════════════════════════════
    "class_diagram": {
        "name": "UML 类图",
        "name_en": "Class Diagram",
        "standard": "OMG UML 2.5.1",
        "template": "USTRME_M.VSTX",
        "stencils": [
            {"file": "USTRME_M.VSSX", "purpose": "类图全部形状与连接器"},
        ],
        "shapes": [
            {"master": "Class", "purpose": "类", "note": "主要元素，包含名称/属性/方法分区"},
            {"master": "Member", "purpose": "成员行", "note": "放置在 Class 内部表示属性或方法"},
            {"master": "Separator", "purpose": "分隔线", "note": "分隔类的属性区和方法区"},
            {"master": "Interface", "purpose": "接口", "note": "带 <<interface>> 构造型"},
            {"master": "Enumeration", "purpose": "枚举", "note": "带 <<enumeration>> 构造型"},
            {"master": "Package (expanded)", "purpose": "包（展开）", "note": "容器，展示内部元素"},
            {"master": "Package (collapsed)", "purpose": "包（折叠）", "note": "紧凑表示"},
            {"master": "Note", "purpose": "注释", "note": "折角矩形"},
            {"master": "Composite", "purpose": "组合结构", "note": "复合结构容器"},
        ],
        "edges": [
            {"master": "Inheritance", "stencil": "USTRME_M.VSSX", "semantic": "泛化/继承", "line": "实线", "arrow": "空心三角", "direction": "子类→父类"},
            {"master": "Interface Realization", "stencil": "USTRME_M.VSSX", "semantic": "接口实现", "line": "虚线", "arrow": "空心三角", "direction": "实现类→接口"},
            {"master": "Association", "stencil": "USTRME_M.VSSX", "semantic": "关联", "line": "实线", "arrow": "无", "direction": "双向关联"},
            {"master": "Directed Association", "stencil": "USTRME_M.VSSX", "semantic": "有向关联", "line": "实线", "arrow": "开放箭头", "direction": "源→目标"},
            {"master": "Aggregation", "stencil": "USTRME_M.VSSX", "semantic": "聚合", "line": "实线", "arrow": "空心菱形", "direction": "部分→整体（菱形在整体端）"},
            {"master": "Composition", "stencil": "USTRME_M.VSSX", "semantic": "组合", "line": "实线", "arrow": "实心菱形", "direction": "部分→整体（菱形在整体端）"},
            {"master": "Dependency", "stencil": "USTRME_M.VSSX", "semantic": "依赖", "line": "虚线", "arrow": "开放箭头", "direction": "依赖方→被依赖方"},
        ],
        "layout": {
            "direction": "top-to-bottom",
            "spacing_h": 2.0,
            "spacing_v": 1.5,
            "notes": [
                "父类居中上方，子类均匀分布在下方",
                "接口放在实现类的上方",
            ],
        },
        "example": {
            "description": "Animal 继承体系：Animal (父类) → Dog, Cat (子类)，展示继承关系和属性",
            "shapes": [
                {"id": "animal", "type": "drop", "master_name": "Class", "stencil_name": "USTRME_M.VSSX", "x": 4.25, "y": 9, "text": "Animal"},
                {"id": "dog", "type": "drop", "master_name": "Class", "stencil_name": "USTRME_M.VSSX", "x": 2.5, "y": 6, "text": "Dog"},
                {"id": "cat", "type": "drop", "master_name": "Class", "stencil_name": "USTRME_M.VSSX", "x": 6, "y": 6, "text": "Cat"},
                {"id": "iswim", "type": "drop", "master_name": "Interface", "stencil_name": "USTRME_M.VSSX", "x": 6, "y": 9, "text": "<<interface>>\nISwimmable"},
            ],
            "connections": [
                {"from": "dog", "to": "animal", "connector_master": "Inheritance", "connector_stencil": "USTRME_M.VSSX"},
                {"from": "cat", "to": "animal", "connector_master": "Inheritance", "connector_stencil": "USTRME_M.VSSX"},
                {"from": "dog", "to": "iswim", "connector_master": "Interface Realization", "connector_stencil": "USTRME_M.VSSX"},
            ],
            "notes": "UML 类图的连接器必须使用 stencil 连接器（如 Inheritance, Composition），不能用 AutoConnect，否则箭头样式错误。",
        },
    },
    "sequence_diagram": {
        "name": "UML 序列图",
        "name_en": "Sequence Diagram",
        "standard": "OMG UML 2.5.1 — Interaction Diagrams",
        "template": "USEQME_M.VSTX",
        "stencils": [
            {"file": "USEQME_M.VSSX", "purpose": "序列图全部形状与消息"},
        ],
        "shapes": [
            {"master": "Object lifeline", "purpose": "对象生命线", "note": "矩形头部 + 虚线"},
            {"master": "Actor lifeline", "purpose": "参与者生命线", "note": "人形图标 + 虚线"},
            {"master": "Activation", "purpose": "激活条", "note": "叠加在生命线上的窄矩形"},
            {"master": "Loop fragment", "purpose": "循环片段", "note": "标记循环区域"},
            {"master": "Optional fragment", "purpose": "可选片段", "note": "opt 区域"},
            {"master": "Alternative fragment", "purpose": "选择片段", "note": "alt 区域（含多分支）"},
            {"master": "Interaction operand", "purpose": "交互操作数", "note": "alt 片段的分支分隔"},
            {"master": "Other fragment", "purpose": "其他片段", "note": "break/critical/neg 等"},
        ],
        "edges": [
            {"master": "Message", "stencil": "USEQME_M.VSSX", "semantic": "同步消息", "line": "实线", "arrow": "实心箭头", "direction": "调用方→被调用方"},
            {"master": "Return Message", "stencil": "USEQME_M.VSSX", "semantic": "返回消息", "line": "虚线", "arrow": "开放箭头", "direction": "被调用方→调用方"},
            {"master": "Self Message", "stencil": "USEQME_M.VSSX", "semantic": "自调用", "line": "实线", "arrow": "实心箭头", "direction": "指向自身的生命线"},
            {"master": "Asynchronous Message", "stencil": "USEQME_M.VSSX", "semantic": "异步消息", "line": "实线", "arrow": "开放箭头", "direction": "非阻塞调用"},
        ],
        "layout": {
            "direction": "left-to-right",
            "spacing_h": 2.0,
            "spacing_v": 0.5,
            "notes": [
                "参与者从左到右排列，时间从上到下流动",
                "生命线等距分布，推荐 2.0~2.5 英寸间距",
                "同一消息的 from_port 和 to_port 使用相同索引，保证起止 Y 坐标相同",
                "不同消息使用递增的连接点索引（如 1, 3, 5, 7），间隔 2 个点约 0.5 英寸",
                "Object lifeline 有 100 个连接点（索引 0-99），沿生命线从上到下分布",
                "消息必须通过 from_port/to_port 连接到生命线上的连接点，而非参与者头部",
            ],
        },
        "example": {
            "description": "用户登录：Client → AuthService → Database 的同步消息交互",
            "shapes": [
                {"id": "client", "type": "drop", "master_name": "Object lifeline", "stencil_name": "USEQME_M.VSSX", "x": 2, "y": 9, "text": "Client"},
                {"id": "auth", "type": "drop", "master_name": "Object lifeline", "stencil_name": "USEQME_M.VSSX", "x": 4.5, "y": 9, "text": "AuthService"},
                {"id": "db", "type": "drop", "master_name": "Object lifeline", "stencil_name": "USEQME_M.VSSX", "x": 7, "y": 9, "text": "Database"},
            ],
            "connections": [
                {"from": "client", "to": "auth", "from_port": 1, "to_port": 1, "connector_master": "Message", "connector_stencil": "USEQME_M.VSSX", "text": "login()"},
                {"from": "auth", "to": "db", "from_port": 3, "to_port": 3, "connector_master": "Message", "connector_stencil": "USEQME_M.VSSX", "text": "query()"},
                {"from": "db", "to": "auth", "from_port": 5, "to_port": 5, "connector_master": "Return Message", "connector_stencil": "USEQME_M.VSSX", "text": "result"},
                {"from": "auth", "to": "client", "from_port": 7, "to_port": 7, "connector_master": "Return Message", "connector_stencil": "USEQME_M.VSSX", "text": "token"},
            ],
            "notes": "序列图的消息必须使用 from_port/to_port 指定连接点索引，将消息胶合到生命线虚线上的特定位置。连接点从 0 开始沿生命线从上到下分布（间隔约 0.25 英寸），不同消息使用不同索引实现时间顺序排列。推荐间隔 2 个索引（约 0.5 英寸）。",
        },
    },
    "activity_diagram": {
        "name": "UML 活动图",
        "name_en": "Activity Diagram",
        "standard": "OMG UML 2.5.1 — Activity Diagrams",
        "template": "UACTME_M.VSTX",
        "stencils": [
            {"file": "UACTME_M.VSSX", "purpose": "活动图形状"},
            {"file": "XFUNC_M.VSSX", "purpose": "跨职能泳道（可选）"},
        ],
        "shapes": [
            {"master": "Initial node", "purpose": "初始节点", "note": "实心圆"},
            {"master": "Action", "purpose": "动作/活动", "note": "圆角矩形"},
            {"master": "Decision", "purpose": "决策", "note": "菱形"},
            {"master": "Merge Node", "purpose": "合并节点", "note": "菱形"},
            {"master": "Fork node", "purpose": "分叉节点", "note": "粗线条（并行开始）"},
            {"master": "Join node", "purpose": "汇合节点", "note": "粗线条（并行结束）"},
            {"master": "Final node", "purpose": "终止节点", "note": "圆内圈实心圆"},
            {"master": "Note", "purpose": "注释", "note": ""},
            {"master": "Swimlane", "purpose": "泳道（水平）", "note": ""},
            {"master": "Swimlane (vertical)", "purpose": "泳道（垂直）", "note": ""},
        ],
        "edges": [
            {"master": "AutoConnect", "stencil": "", "semantic": "控制流", "line": "实线", "arrow": "箭头", "direction": "活动之间默认箭头连接"},
        ],
        "layout": {
            "direction": "top-to-bottom",
            "spacing_h": 2.0,
            "spacing_v": 1.0,
            "notes": [
                "Decision 分支：Yes/No 分别向左右",
                "Fork/Join 水平放置，宽度与并行分支总宽度对齐",
            ],
        },
        "example": {
            "description": "订单处理流程：接收订单 → 检查库存(决策) → 发货/通知缺货 → 结束",
            "shapes": [
                {"id": "start", "type": "drop", "master_name": "Initial node", "stencil_name": "UACTME_M.VSSX", "x": 4.25, "y": 10},
                {"id": "receive", "type": "drop", "master_name": "Action", "stencil_name": "UACTME_M.VSSX", "x": 4.25, "y": 8.5, "text": "Receive Order"},
                {"id": "check", "type": "drop", "master_name": "Decision", "stencil_name": "UACTME_M.VSSX", "x": 4.25, "y": 7, "text": "In Stock?"},
                {"id": "ship", "type": "drop", "master_name": "Action", "stencil_name": "UACTME_M.VSSX", "x": 2.5, "y": 5.5, "text": "Ship Order"},
                {"id": "notify", "type": "drop", "master_name": "Action", "stencil_name": "UACTME_M.VSSX", "x": 6, "y": 5.5, "text": "Notify Out of Stock"},
                {"id": "merge", "type": "drop", "master_name": "Merge Node", "stencil_name": "UACTME_M.VSSX", "x": 4.25, "y": 4},
                {"id": "end", "type": "drop", "master_name": "Final node", "stencil_name": "UACTME_M.VSSX", "x": 4.25, "y": 2.5},
            ],
            "connections": [
                {"from": "start", "to": "receive"},
                {"from": "receive", "to": "check"},
                {"from": "check", "to": "ship"},
                {"from": "check", "to": "notify"},
                {"from": "ship", "to": "merge"},
                {"from": "notify", "to": "merge"},
                {"from": "merge", "to": "end"},
            ],
            "notes": "活动图使用 AutoConnect（不传 connector_master）。Decision 和 Merge Node 都是菱形，语义不同但形状相同。",
        },
    },
    "state_machine_diagram": {
        "name": "UML 状态机图",
        "name_en": "State Machine Diagram",
        "standard": "OMG UML 2.5.1 — State Machine Diagrams",
        "template": "USTAME_M.VSTX",
        "stencils": [
            {"file": "USTAME_M.VSSX", "purpose": "状态机图全部形状"},
        ],
        "shapes": [
            {"master": "State", "purpose": "简单状态", "note": "圆角矩形"},
            {"master": "State with internal behavior", "purpose": "带内部行为的状态", "note": "含 entry/do/exit 分区"},
            {"master": "Composite state", "purpose": "复合状态", "note": "包含子状态的容器"},
            {"master": "Submachine state", "purpose": "子状态机", "note": "引用其他状态机"},
            {"master": "Initial state", "purpose": "初始状态", "note": "实心圆"},
            {"master": "Final state", "purpose": "终止状态", "note": "圆内实心圆"},
            {"master": "Choice", "purpose": "选择伪状态", "note": "菱形"},
            {"master": "Note", "purpose": "注释", "note": ""},
        ],
        "edges": [
            {"master": "AutoConnect", "stencil": "", "semantic": "状态转换", "line": "实线", "arrow": "箭头", "direction": "在连接线上标注触发事件/条件/动作"},
        ],
        "layout": {
            "direction": "top-to-bottom",
            "spacing_h": 2.0,
            "spacing_v": 1.5,
            "notes": [
                "Initial state 在顶部，Final state 在底部",
                "复合状态内部子状态使用缩进布局",
            ],
        },
        "example": {
            "description": "订单状态机：New → Confirmed → Shipped → Delivered，含取消分支",
            "shapes": [
                {"id": "init", "type": "drop", "master_name": "Initial state", "stencil_name": "USTAME_M.VSSX", "x": 4.25, "y": 10},
                {"id": "new", "type": "drop", "master_name": "State", "stencil_name": "USTAME_M.VSSX", "x": 4.25, "y": 8.5, "text": "New"},
                {"id": "confirmed", "type": "drop", "master_name": "State", "stencil_name": "USTAME_M.VSSX", "x": 4.25, "y": 7, "text": "Confirmed"},
                {"id": "shipped", "type": "drop", "master_name": "State", "stencil_name": "USTAME_M.VSSX", "x": 4.25, "y": 5.5, "text": "Shipped"},
                {"id": "delivered", "type": "drop", "master_name": "State", "stencil_name": "USTAME_M.VSSX", "x": 4.25, "y": 4, "text": "Delivered"},
                {"id": "cancelled", "type": "drop", "master_name": "State", "stencil_name": "USTAME_M.VSSX", "x": 7, "y": 7, "text": "Cancelled"},
                {"id": "final", "type": "drop", "master_name": "Final state", "stencil_name": "USTAME_M.VSSX", "x": 4.25, "y": 2.5},
            ],
            "connections": [
                {"from": "init", "to": "new"},
                {"from": "new", "to": "confirmed"},
                {"from": "confirmed", "to": "shipped"},
                {"from": "shipped", "to": "delivered"},
                {"from": "delivered", "to": "final"},
                {"from": "new", "to": "cancelled"},
                {"from": "cancelled", "to": "final"},
            ],
            "notes": "状态机图使用 AutoConnect。转换条件可在连接后通过 set_shape_text 设置连接器文本。",
        },
    },
    "use_case_diagram": {
        "name": "UML 用例图",
        "name_en": "Use Case Diagram",
        "standard": "OMG UML 2.5.1 — Use Case Diagrams",
        "template": "UUSEME_M.VSTX",
        "stencils": [
            {"file": "UUSEME_M.VSSX", "purpose": "用例图全部形状与连接器"},
        ],
        "shapes": [
            {"master": "Actor", "purpose": "参与者", "note": "人形图标"},
            {"master": "Use Case", "purpose": "用例", "note": "椭圆形"},
            {"master": "Subsystem", "purpose": "子系统边界", "note": "矩形容器"},
        ],
        "edges": [
            {"master": "Association", "stencil": "UUSEME_M.VSSX", "semantic": "关联", "line": "实线", "arrow": "无", "direction": "参与者与用例之间"},
            {"master": "Generalization", "stencil": "UUSEME_M.VSSX", "semantic": "泛化", "line": "实线", "arrow": "空心三角", "direction": "子级→父级"},
            {"master": "Include", "stencil": "UUSEME_M.VSSX", "semantic": "包含", "line": "虚线", "arrow": "开放箭头", "direction": "基础用例→被包含用例；标注 <<include>>"},
            {"master": "Extend", "stencil": "UUSEME_M.VSSX", "semantic": "扩展", "line": "虚线", "arrow": "开放箭头", "direction": "扩展用例→基础用例；标注 <<extend>>"},
            {"master": "Dependency", "stencil": "UUSEME_M.VSSX", "semantic": "依赖", "line": "虚线", "arrow": "开放箭头", "direction": "通用依赖"},
        ],
        "layout": {
            "direction": "center",
            "spacing_h": 2.0,
            "spacing_v": 1.5,
            "notes": [
                "主要参与者在左侧，次要参与者/外部系统在右侧",
                "用例居中，包含在 Subsystem 边界内",
            ],
        },
        "example": {
            "description": "在线商店：Customer 和 Admin 参与者，包含浏览商品、下单、管理商品用例及 Include 关系",
            "shapes": [
                {"id": "customer", "type": "drop", "master_name": "Actor", "stencil_name": "UUSEME_M.VSSX", "x": 1, "y": 7, "text": "Customer"},
                {"id": "admin", "type": "drop", "master_name": "Actor", "stencil_name": "UUSEME_M.VSSX", "x": 7.5, "y": 7, "text": "Admin"},
                {"id": "browse", "type": "drop", "master_name": "Use Case", "stencil_name": "UUSEME_M.VSSX", "x": 4.25, "y": 9, "text": "Browse Products"},
                {"id": "order", "type": "drop", "master_name": "Use Case", "stencil_name": "UUSEME_M.VSSX", "x": 4.25, "y": 7, "text": "Place Order"},
                {"id": "pay", "type": "drop", "master_name": "Use Case", "stencil_name": "UUSEME_M.VSSX", "x": 4.25, "y": 5, "text": "Make Payment"},
                {"id": "manage", "type": "drop", "master_name": "Use Case", "stencil_name": "UUSEME_M.VSSX", "x": 4.25, "y": 3, "text": "Manage Products"},
            ],
            "connections": [
                {"from": "customer", "to": "browse", "connector_master": "Association", "connector_stencil": "UUSEME_M.VSSX"},
                {"from": "customer", "to": "order", "connector_master": "Association", "connector_stencil": "UUSEME_M.VSSX"},
                {"from": "order", "to": "pay", "connector_master": "Include", "connector_stencil": "UUSEME_M.VSSX"},
                {"from": "admin", "to": "manage", "connector_master": "Association", "connector_stencil": "UUSEME_M.VSSX"},
            ],
            "notes": "用例图的连接器必须使用 stencil 连接器。Association 用于参与者-用例连接，Include/Extend 用于用例间关系。",
        },
    },
    "component_diagram": {
        "name": "UML 组件图",
        "name_en": "Component Diagram",
        "standard": "OMG UML 2.5.1 — Component Diagrams",
        "template": "UCOMME_M.VSTX",
        "stencils": [
            {"file": "UCOMME_M.VSSX", "purpose": "组件图全部形状与连接器"},
        ],
        "shapes": [
            {"master": "Component", "purpose": "组件", "note": "带组件图标的矩形"},
            {"master": "Provided Interface", "purpose": "提供的接口", "note": "棒棒糖符号 (lollipop)"},
            {"master": "Required Interface", "purpose": "需要的接口", "note": "半圆符号 (socket)"},
            {"master": "Package", "purpose": "包", "note": "容器"},
            {"master": "Note", "purpose": "注释", "note": ""},
            {"master": "Composite", "purpose": "组合结构", "note": "容器"},
        ],
        "edges": [
            {"master": "Association", "stencil": "UCOMME_M.VSSX", "semantic": "关联", "line": "实线", "arrow": "无", "direction": ""},
            {"master": "Directed Association", "stencil": "UCOMME_M.VSSX", "semantic": "有向关联", "line": "实线", "arrow": "开放箭头", "direction": ""},
            {"master": "Dependency", "stencil": "UCOMME_M.VSSX", "semantic": "依赖", "line": "虚线", "arrow": "开放箭头", "direction": ""},
            {"master": "Aggregation", "stencil": "UCOMME_M.VSSX", "semantic": "聚合", "line": "实线", "arrow": "空心菱形", "direction": ""},
            {"master": "Composition", "stencil": "UCOMME_M.VSSX", "semantic": "组合", "line": "实线", "arrow": "实心菱形", "direction": ""},
        ],
        "layout": {
            "direction": "free",
            "spacing_h": 2.0,
            "spacing_v": 2.0,
            "notes": [
                "高层组件在上",
                "Provided/Required Interface 放置在组件边缘",
            ],
        },
        "example": {
            "description": "三层架构：WebUI → API Server → Database 组件，使用依赖关系",
            "shapes": [
                {"id": "ui", "type": "drop", "master_name": "Component", "stencil_name": "UCOMME_M.VSSX", "x": 4.25, "y": 9, "text": "WebUI"},
                {"id": "api", "type": "drop", "master_name": "Component", "stencil_name": "UCOMME_M.VSSX", "x": 4.25, "y": 6.5, "text": "API Server"},
                {"id": "db", "type": "drop", "master_name": "Component", "stencil_name": "UCOMME_M.VSSX", "x": 4.25, "y": 4, "text": "Database"},
            ],
            "connections": [
                {"from": "ui", "to": "api", "connector_master": "Dependency", "connector_stencil": "UCOMME_M.VSSX"},
                {"from": "api", "to": "db", "connector_master": "Dependency", "connector_stencil": "UCOMME_M.VSSX"},
            ],
            "notes": "组件图的连接器使用 stencil 连接器。Dependency 表示依赖关系（虚线箭头）。",
        },
    },
    "deployment_diagram": {
        "name": "UML 部署图",
        "name_en": "Deployment Diagram",
        "standard": "OMG UML 2.5.1 — Deployment Diagrams",
        "template": "UDEPME_M.VSTX",
        "stencils": [
            {"file": "UDEPME_M.VSSX", "purpose": "部署图全部形状与连接器"},
        ],
        "shapes": [
            {"master": "Node", "purpose": "节点", "note": "3D 立方体，表示物理/虚拟主机"},
            {"master": "Node Instance", "purpose": "节点实例", "note": "带下划线名称"},
            {"master": "Artifact", "purpose": "制品", "note": "文件/JAR/DLL 等可部署单元"},
            {"master": "Artifact Instance", "purpose": "制品实例", "note": ""},
            {"master": "Component", "purpose": "组件", "note": "嵌套在节点内"},
            {"master": "Component Instance", "purpose": "组件实例", "note": ""},
            {"master": "Deployment Spec", "purpose": "部署规格", "note": "配置描述"},
            {"master": "Deployment Spec Instance", "purpose": "部署规格实例", "note": ""},
            {"master": "Package", "purpose": "包", "note": "容器"},
            {"master": "Provided Interface", "purpose": "提供的接口", "note": ""},
            {"master": "Required Interface", "purpose": "需要的接口", "note": ""},
            {"master": "Note", "purpose": "注释", "note": ""},
            {"master": "Diagram Overview", "purpose": "图总览", "note": ""},
            {"master": "Composite", "purpose": "组合结构", "note": ""},
        ],
        "edges": [
            {"master": "Association", "stencil": "UDEPME_M.VSSX", "semantic": "通信路径", "line": "实线", "arrow": "无", "direction": ""},
            {"master": "Directed Association", "stencil": "UDEPME_M.VSSX", "semantic": "有向通信", "line": "实线", "arrow": "开放箭头", "direction": ""},
            {"master": "Dependency", "stencil": "UDEPME_M.VSSX", "semantic": "依赖", "line": "虚线", "arrow": "开放箭头", "direction": ""},
            {"master": "Aggregation", "stencil": "UDEPME_M.VSSX", "semantic": "聚合", "line": "实线", "arrow": "空心菱形", "direction": ""},
            {"master": "Composition", "stencil": "UDEPME_M.VSSX", "semantic": "组合", "line": "实线", "arrow": "实心菱形", "direction": ""},
            {"master": "Deploy", "stencil": "UDEPME_M.VSSX", "semantic": "部署", "line": "虚线", "arrow": "开放箭头", "direction": ""},
            {"master": "Manifest", "stencil": "UDEPME_M.VSSX", "semantic": "表现", "line": "虚线", "arrow": "开放箭头", "direction": ""},
        ],
        "layout": {
            "direction": "free",
            "spacing_h": 2.5,
            "spacing_v": 2.5,
            "notes": [
                "Artifact/Component 放置在 Node 内部",
            ],
        },
        "example": {
            "description": "Web 应用部署：Web Server 节点 → App Server 节点 → DB Server 节点",
            "shapes": [
                {"id": "web", "type": "drop", "master_name": "Node", "stencil_name": "UDEPME_M.VSSX", "x": 2, "y": 8, "text": "<<device>>\nWeb Server"},
                {"id": "app", "type": "drop", "master_name": "Node", "stencil_name": "UDEPME_M.VSSX", "x": 4.25, "y": 5.5, "text": "<<device>>\nApp Server"},
                {"id": "dbsrv", "type": "drop", "master_name": "Node", "stencil_name": "UDEPME_M.VSSX", "x": 6.5, "y": 3, "text": "<<device>>\nDB Server"},
                {"id": "war", "type": "drop", "master_name": "Artifact", "stencil_name": "UDEPME_M.VSSX", "x": 4.25, "y": 4, "text": "app.war"},
            ],
            "connections": [
                {"from": "web", "to": "app", "connector_master": "Association", "connector_stencil": "UDEPME_M.VSSX"},
                {"from": "app", "to": "dbsrv", "connector_master": "Association", "connector_stencil": "UDEPME_M.VSSX"},
                {"from": "war", "to": "app", "connector_master": "Deploy", "connector_stencil": "UDEPME_M.VSSX"},
            ],
            "notes": "部署图使用 stencil 连接器。Association 表示通信路径，Deploy 表示部署关系。Artifact 应放在 Node 附近。",
        },
    },

    # ═══════════════════════════════════════════════════════════════
    # Flowcharts & BPMN
    # ═══════════════════════════════════════════════════════════════
    "flowchart": {
        "name": "基本流程图",
        "name_en": "Flowchart",
        "standard": "ISO 5807 / ANSI Flowchart Standard",
        "template": "BASFLO_M.VSTX",
        "stencils": [
            {"file": "BASFLO_M.VSSX", "purpose": "基本流程图形状（推荐）"},
            {"file": "FLOSHP_M.VSSX", "purpose": "详细流程图扩展形状（56 种）"},
        ],
        "shapes": [
            {"master": "Start/End", "purpose": "起止符", "note": "圆角矩形/胶囊形"},
            {"master": "Process", "purpose": "处理步骤", "note": "矩形"},
            {"master": "Decision", "purpose": "判定", "note": "菱形"},
            {"master": "Subprocess", "purpose": "子流程/预定义处理", "note": "双竖线矩形"},
            {"master": "Document", "purpose": "文档", "note": "波浪底边矩形"},
            {"master": "Data", "purpose": "数据 (I/O)", "note": "平行四边形"},
            {"master": "Database", "purpose": "数据库", "note": "圆柱体"},
            {"master": "External Data", "purpose": "外部数据", "note": ""},
            {"master": "On-page reference", "purpose": "页内引用", "note": "小圆形"},
            {"master": "Off-page reference", "purpose": "跨页引用", "note": "五边形"},
        ],
        "edges": [
            {"master": "AutoConnect", "stencil": "", "semantic": "流程连接", "line": "实线", "arrow": "箭头", "direction": "推荐使用"},
            {"master": "Dynamic connector", "stencil": "BASFLO_M.VSSX", "semantic": "流程连接", "line": "实线", "arrow": "箭头", "direction": "需要更多控制时使用"},
        ],
        "layout": {
            "direction": "top-to-bottom",
            "spacing_h": 2.0,
            "spacing_v": 1.0,
            "notes": [
                "Decision 分支：Yes 向下，No 向右（保持一致即可）",
                "分支最终汇入同一路径",
                "主流程居中对齐",
            ],
        },
        "example": {
            "description": "审批流程：Start → 提交申请 → 审核 → 是否批准(Decision) → 批准处理/驳回 → End",
            "shapes": [
                {"id": "start", "type": "drop", "master_name": "Start/End", "stencil_name": "BASFLO_M.VSSX", "x": 4.25, "y": 10, "text": "Start"},
                {"id": "submit", "type": "drop", "master_name": "Process", "stencil_name": "BASFLO_M.VSSX", "x": 4.25, "y": 8.5, "text": "Submit Request"},
                {"id": "review", "type": "drop", "master_name": "Process", "stencil_name": "BASFLO_M.VSSX", "x": 4.25, "y": 7, "text": "Review Request"},
                {"id": "decide", "type": "drop", "master_name": "Decision", "stencil_name": "BASFLO_M.VSSX", "x": 4.25, "y": 5.5, "text": "Approved?"},
                {"id": "approve", "type": "drop", "master_name": "Process", "stencil_name": "BASFLO_M.VSSX", "x": 2.5, "y": 4, "text": "Process Approval"},
                {"id": "reject", "type": "drop", "master_name": "Process", "stencil_name": "BASFLO_M.VSSX", "x": 6, "y": 4, "text": "Send Rejection"},
                {"id": "end", "type": "drop", "master_name": "Start/End", "stencil_name": "BASFLO_M.VSSX", "x": 4.25, "y": 2, "text": "End"},
            ],
            "connections": [
                {"from": "start", "to": "submit"},
                {"from": "submit", "to": "review"},
                {"from": "review", "to": "decide"},
                {"from": "decide", "to": "approve"},
                {"from": "decide", "to": "reject"},
                {"from": "approve", "to": "end"},
                {"from": "reject", "to": "end"},
            ],
            "notes": "流程图使用 AutoConnect（不传 connector_master）。Start/End 用同一个 master，通过文本区分。",
        },
    },
    "cross_functional_flowchart": {
        "name": "跨职能流程图",
        "name_en": "Cross-Functional Flowchart / Swimlane",
        "standard": "BPMN 泳道映射 / 企业流程建模规范",
        "template": "XFUNC_M.VSTX",
        "stencils": [
            {"file": "XFUNC_M.VSSX", "purpose": "泳道容器"},
            {"file": "BASFLO_M.VSSX", "purpose": "流程形状"},
        ],
        "shapes": [
            {"master": "CFF Container", "purpose": "跨职能流程图容器", "note": "XFUNC_M.VSSX"},
            {"master": "Swimlane", "purpose": "泳道（水平）", "note": "XFUNC_M.VSSX"},
            {"master": "Swimlane (vertical)", "purpose": "泳道（垂直）", "note": "XFUNC_M.VSSX"},
            {"master": "Separator", "purpose": "泳道分隔线", "note": "XFUNC_M.VSSX"},
            {"master": "Separator (vertical)", "purpose": "泳道分隔线（垂直）", "note": "XFUNC_M.VSSX"},
            {"master": "Swimlane List", "purpose": "泳道列表容器", "note": "XFUNC_M.VSSX"},
            {"master": "Phase List", "purpose": "阶段列表", "note": "XFUNC_M.VSSX"},
        ],
        "edges": [
            {"master": "AutoConnect", "stencil": "", "semantic": "流程连接", "line": "实线", "arrow": "箭头", "direction": "泳道内和跨泳道"},
        ],
        "layout": {
            "direction": "top-to-bottom",
            "spacing_h": 2.0,
            "spacing_v": 1.0,
            "notes": [
                "泳道水平排列时，流程从上到下",
                "泳道垂直排列时，流程从左到右",
                "推荐泳道最小宽度 2.0 英寸",
                "跨泳道连线保持水平/垂直正交",
            ],
        },
        "example": {
            "description": "采购流程：跨 Requester / Manager / Finance 三个泳道的审批流程",
            "shapes": [
                {"id": "start", "type": "drop", "master_name": "Start/End", "stencil_name": "BASFLO_M.VSSX", "x": 2, "y": 9, "text": "Start"},
                {"id": "request", "type": "drop", "master_name": "Process", "stencil_name": "BASFLO_M.VSSX", "x": 2, "y": 7.5, "text": "Create PO"},
                {"id": "approve", "type": "drop", "master_name": "Decision", "stencil_name": "BASFLO_M.VSSX", "x": 4.25, "y": 7.5, "text": "Approve?"},
                {"id": "pay", "type": "drop", "master_name": "Process", "stencil_name": "BASFLO_M.VSSX", "x": 6.5, "y": 7.5, "text": "Process Payment"},
                {"id": "revise", "type": "drop", "master_name": "Process", "stencil_name": "BASFLO_M.VSSX", "x": 4.25, "y": 5.5, "text": "Revise PO"},
                {"id": "end", "type": "drop", "master_name": "Start/End", "stencil_name": "BASFLO_M.VSSX", "x": 6.5, "y": 5.5, "text": "End"},
            ],
            "connections": [
                {"from": "start", "to": "request"},
                {"from": "request", "to": "approve"},
                {"from": "approve", "to": "pay"},
                {"from": "approve", "to": "revise"},
                {"from": "revise", "to": "approve"},
                {"from": "pay", "to": "end"},
            ],
            "notes": "跨职能流程图需要先手动放置泳道容器（CFF Container + Swimlane），再在泳道区域内放置流程形状。流程形状使用 BASFLO_M.VSSX。",
        },
    },
    "bpmn": {
        "name": "BPMN 流程图",
        "name_en": "Business Process Model and Notation",
        "standard": "BPMN 2.0 (OMG)",
        "template": "BPMN_M.VSTX",
        "stencils": [
            {"file": "BPMN_M.VSSX", "purpose": "BPMN 全部形状和连接器"},
        ],
        "shapes": [
            {"master": "Start Event", "purpose": "开始事件", "note": "细线圆形"},
            {"master": "Intermediate Event", "purpose": "中间事件", "note": "双线圆形"},
            {"master": "End Event", "purpose": "结束事件", "note": "粗线圆形"},
            {"master": "Task", "purpose": "任务", "note": "圆角矩形"},
            {"master": "Gateway", "purpose": "网关", "note": "菱形（排他/并行/包容）"},
            {"master": "Collapsed Sub-Process", "purpose": "折叠子流程", "note": "带 + 号的圆角矩形"},
            {"master": "Expanded Sub-Process", "purpose": "展开子流程", "note": "大圆角矩形容器"},
            {"master": "Data Object", "purpose": "数据对象", "note": "折角文档"},
            {"master": "Data Store", "purpose": "数据存储", "note": "圆柱体"},
            {"master": "Message", "purpose": "消息", "note": "信封图标"},
            {"master": "Group", "purpose": "分组", "note": "虚线圆角矩形"},
            {"master": "Text Annotation", "purpose": "文本注释", "note": "开放方括号 + 文字"},
            {"master": "Pool / Lane", "purpose": "池/泳道", "note": "带标题的容器"},
        ],
        "edges": [
            {"master": "Sequence Flow", "stencil": "BPMN_M.VSSX", "semantic": "顺序流", "line": "实线", "arrow": "实心箭头", "direction": "同一池内的活动连接"},
            {"master": "Message Flow", "stencil": "BPMN_M.VSSX", "semantic": "消息流", "line": "虚线", "arrow": "开放箭头", "direction": "跨池的消息传递"},
            {"master": "Association", "stencil": "BPMN_M.VSSX", "semantic": "关联", "line": "点线", "arrow": "无/开放箭头", "direction": "连接 Data Object/Annotation"},
        ],
        "layout": {
            "direction": "left-to-right",
            "spacing_h": 1.5,
            "spacing_v": 1.5,
            "notes": [
                "池内流程从左到右",
                "池上下堆叠",
                "网关出口需有条件标注",
                "消息流仅跨池使用，不可在同一池内使用",
            ],
        },
        "example": {
            "description": "订单履行 BPMN：Start Event → Receive Order → Check Stock(Gateway) → Ship/Reorder → End Event",
            "shapes": [
                {"id": "start", "type": "drop", "master_name": "Start Event", "stencil_name": "BPMN_M.VSSX", "x": 1, "y": 5.5, "text": ""},
                {"id": "receive", "type": "drop", "master_name": "Task", "stencil_name": "BPMN_M.VSSX", "x": 2.5, "y": 5.5, "text": "Receive Order"},
                {"id": "gw", "type": "drop", "master_name": "Gateway", "stencil_name": "BPMN_M.VSSX", "x": 4.25, "y": 5.5},
                {"id": "ship", "type": "drop", "master_name": "Task", "stencil_name": "BPMN_M.VSSX", "x": 6, "y": 7, "text": "Ship Order"},
                {"id": "reorder", "type": "drop", "master_name": "Task", "stencil_name": "BPMN_M.VSSX", "x": 6, "y": 4, "text": "Reorder Stock"},
                {"id": "gw2", "type": "drop", "master_name": "Gateway", "stencil_name": "BPMN_M.VSSX", "x": 7.5, "y": 5.5},
                {"id": "end", "type": "drop", "master_name": "End Event", "stencil_name": "BPMN_M.VSSX", "x": 9, "y": 5.5},
            ],
            "connections": [
                {"from": "start", "to": "receive", "connector_master": "Sequence Flow", "connector_stencil": "BPMN_M.VSSX"},
                {"from": "receive", "to": "gw", "connector_master": "Sequence Flow", "connector_stencil": "BPMN_M.VSSX"},
                {"from": "gw", "to": "ship", "connector_master": "Sequence Flow", "connector_stencil": "BPMN_M.VSSX"},
                {"from": "gw", "to": "reorder", "connector_master": "Sequence Flow", "connector_stencil": "BPMN_M.VSSX"},
                {"from": "ship", "to": "gw2", "connector_master": "Sequence Flow", "connector_stencil": "BPMN_M.VSSX"},
                {"from": "reorder", "to": "gw2", "connector_master": "Sequence Flow", "connector_stencil": "BPMN_M.VSSX"},
                {"from": "gw2", "to": "end", "connector_master": "Sequence Flow", "connector_stencil": "BPMN_M.VSSX"},
            ],
            "notes": "BPMN 必须使用 Sequence Flow 连接器（同一池内）。跨池通信使用 Message Flow。Gateway 的出口条件通过连接器文本标注。",
        },
    },

    # ═══════════════════════════════════════════════════════════════
    # Database / ERD
    # ═══════════════════════════════════════════════════════════════
    "erd_crows_foot": {
        "name": "数据库 ER 图 — Crow's Foot 记法",
        "name_en": "ERD — Crow's Foot Notation",
        "standard": "Entity-Relationship Model / Crow's Foot (IE) Notation",
        "template": "DBCROW_M.VSTX",
        "stencils": [
            {"file": "DBCROW_M.VSSX", "purpose": "Crow's Foot 记法 ER 图"},
        ],
        "shapes": [
            {"master": "Entity", "purpose": "实体", "note": "表名标题框"},
            {"master": "Entity With Attributes", "purpose": "带属性的实体", "note": "包含属性列表"},
            {"master": "Attribute", "purpose": "属性", "note": "放置在实体内"},
            {"master": "Primary Key Attribute", "purpose": "主键属性", "note": "带下划线"},
            {"master": "Primary Key Separator", "purpose": "主键分隔线", "note": "分隔 PK 与普通属性"},
        ],
        "edges": [
            {"master": "Relationship", "stencil": "DBCROW_M.VSSX", "semantic": "关系", "line": "实线", "arrow": "Crow's Foot 符号", "direction": "线端自带基数标记"},
        ],
        "layout": {
            "direction": "free",
            "spacing_h": 2.5,
            "spacing_v": 2.5,
            "notes": [
                "网格对齐",
                "关系线保持正交走线",
            ],
        },
        "example": {
            "description": "电商数据库：Users → Orders → Products 三个实体及关系",
            "shapes": [
                {"id": "users", "type": "drop", "master_name": "Entity", "stencil_name": "DBCROW_M.VSSX", "x": 2, "y": 7, "text": "Users"},
                {"id": "orders", "type": "drop", "master_name": "Entity", "stencil_name": "DBCROW_M.VSSX", "x": 4.25, "y": 7, "text": "Orders"},
                {"id": "products", "type": "drop", "master_name": "Entity", "stencil_name": "DBCROW_M.VSSX", "x": 6.5, "y": 7, "text": "Products"},
            ],
            "connections": [
                {"from": "users", "to": "orders", "connector_master": "Relationship", "connector_stencil": "DBCROW_M.VSSX"},
                {"from": "orders", "to": "products", "connector_master": "Relationship", "connector_stencil": "DBCROW_M.VSSX"},
            ],
            "notes": "Crow's Foot ER 图使用 Relationship 连接器，线端自带基数标记（Crow's Foot 符号）。可使用 Entity With Attributes 显示字段。",
        },
    },
    "erd_chen": {
        "name": "数据库 ER 图 — Chen 记法",
        "name_en": "ERD — Chen Notation",
        "standard": "Peter Chen (1976) ER Model",
        "template": "DBCHEN_M.VSTX",
        "stencils": [
            {"file": "DBCHEN_M.VSSX", "purpose": "Chen 记法 ER 图"},
        ],
        "shapes": [
            {"master": "Entity", "purpose": "实体", "note": "矩形"},
            {"master": "Weak Entity", "purpose": "弱实体", "note": "双线矩形"},
            {"master": "Associative Entity ", "purpose": "关联实体", "note": "注意：master 名称末尾有空格"},
            {"master": "Attribute", "purpose": "属性", "note": "椭圆"},
            {"master": "Primary Key attribute ", "purpose": "主键属性", "note": "带下划线椭圆；名称末尾有空格"},
            {"master": "Multi-valued Attribute ", "purpose": "多值属性", "note": "双线椭圆；名称末尾有空格"},
            {"master": "Derived Attribute", "purpose": "派生属性", "note": "虚线椭圆"},
        ],
        "edges": [
            {"master": "Relationship", "stencil": "DBCHEN_M.VSSX", "semantic": "关系", "line": "实线", "arrow": "无", "direction": "菱形符号"},
            {"master": "Identifying Relationship", "stencil": "DBCHEN_M.VSSX", "semantic": "标识关系", "line": "实线", "arrow": "无", "direction": "双线菱形"},
            {"master": "Relationship Connector", "stencil": "DBCHEN_M.VSSX", "semantic": "关系连接线", "line": "实线", "arrow": "无", "direction": "连接属性/实体到关系"},
        ],
        "layout": {
            "direction": "free",
            "spacing_h": 2.0,
            "spacing_v": 2.0,
            "notes": [
                "属性围绕实体辐射排列",
                "关系菱形放在连接的实体之间",
            ],
        },
        "example": {
            "description": "学生选课：Student 和 Course 实体，Enrolls 关系，含属性",
            "shapes": [
                {"id": "student", "type": "drop", "master_name": "Entity", "stencil_name": "DBCHEN_M.VSSX", "x": 2, "y": 5.5, "text": "Student"},
                {"id": "course", "type": "drop", "master_name": "Entity", "stencil_name": "DBCHEN_M.VSSX", "x": 7, "y": 5.5, "text": "Course"},
                {"id": "enrolls", "type": "drop", "master_name": "Relationship", "stencil_name": "DBCHEN_M.VSSX", "x": 4.5, "y": 5.5, "text": "Enrolls"},
                {"id": "sid", "type": "drop", "master_name": "Primary Key attribute ", "stencil_name": "DBCHEN_M.VSSX", "x": 1, "y": 7.5, "text": "StudentID"},
                {"id": "sname", "type": "drop", "master_name": "Attribute", "stencil_name": "DBCHEN_M.VSSX", "x": 3, "y": 7.5, "text": "Name"},
                {"id": "cid", "type": "drop", "master_name": "Primary Key attribute ", "stencil_name": "DBCHEN_M.VSSX", "x": 6, "y": 7.5, "text": "CourseID"},
                {"id": "ctitle", "type": "drop", "master_name": "Attribute", "stencil_name": "DBCHEN_M.VSSX", "x": 8, "y": 7.5, "text": "Title"},
            ],
            "connections": [
                {"from": "student", "to": "enrolls", "connector_master": "Relationship Connector", "connector_stencil": "DBCHEN_M.VSSX"},
                {"from": "enrolls", "to": "course", "connector_master": "Relationship Connector", "connector_stencil": "DBCHEN_M.VSSX"},
                {"from": "student", "to": "sid", "connector_master": "Relationship Connector", "connector_stencil": "DBCHEN_M.VSSX"},
                {"from": "student", "to": "sname", "connector_master": "Relationship Connector", "connector_stencil": "DBCHEN_M.VSSX"},
                {"from": "course", "to": "cid", "connector_master": "Relationship Connector", "connector_stencil": "DBCHEN_M.VSSX"},
                {"from": "course", "to": "ctitle", "connector_master": "Relationship Connector", "connector_stencil": "DBCHEN_M.VSSX"},
            ],
            "notes": "注意 Chen 记法中部分 master 名称末尾有空格：'Primary Key attribute '、'Associative Entity '、'Multi-valued Attribute '。必须包含该空格。",
        },
    },

    # ═══════════════════════════════════════════════════════════════
    # Network
    # ═══════════════════════════════════════════════════════════════
    "network_diagram": {
        "name": "网络拓扑图",
        "name_en": "Network Diagram",
        "standard": "Cisco Systems 图标规范 / ITU-T",
        "template": "NETW_M.VSTX",
        "stencils": [
            {"file": "PERIPH_M.VSSX", "purpose": "基本网络与外设（推荐通用场景）"},
            {"file": "NETSYM_M.VSSX", "purpose": "网络设备符号"},
            {"file": "CISCONETWORKSHAPES_M.VSSX", "purpose": "Cisco 专用图标（292 种）"},
            {"file": "NETLOC_M.VSSX", "purpose": "网络位置（Cloud, Building 等）"},
            {"file": "NETLME_M.VSSX", "purpose": "网络逻辑位置"},
            {"file": "COMPS_M.VSSX", "purpose": "计算机与显示器"},
            {"file": "SERVER_M.VSSX", "purpose": "服务器类型"},
        ],
        "shapes": [
            {"master": "Server", "purpose": "服务器", "note": "PERIPH_M.VSSX"},
            {"master": "Router", "purpose": "路由器", "note": "PERIPH_M.VSSX"},
            {"master": "Switch", "purpose": "交换机", "note": "PERIPH_M.VSSX"},
            {"master": "Firewall", "purpose": "防火墙", "note": "PERIPH_M.VSSX"},
            {"master": "Hub", "purpose": "集线器", "note": "PERIPH_M.VSSX"},
            {"master": "Bridge", "purpose": "网桥", "note": "PERIPH_M.VSSX"},
            {"master": "Modem", "purpose": "调制解调器", "note": "PERIPH_M.VSSX"},
            {"master": "Wireless access point", "purpose": "无线接入点", "note": "PERIPH_M.VSSX"},
            {"master": "Ethernet", "purpose": "以太网总线", "note": "PERIPH_M.VSSX"},
            {"master": "Mainframe", "purpose": "大型机", "note": "PERIPH_M.VSSX"},
            {"master": "Printer", "purpose": "打印机", "note": "PERIPH_M.VSSX"},
            {"master": "User", "purpose": "用户", "note": "PERIPH_M.VSSX"},
            {"master": "Cloud", "purpose": "云/互联网", "note": "NETLOC_M.VSSX"},
            {"master": "Building", "purpose": "办公楼", "note": "NETLOC_M.VSSX"},
            {"master": "Data Center", "purpose": "数据中心", "note": "NETLME_M.VSSX"},
        ],
        "edges": [
            {"master": "AutoConnect", "stencil": "", "semantic": "网络链路", "line": "实线", "arrow": "无", "direction": "通常使用无箭头直线"},
            {"master": "Dynamic connector", "stencil": "PERIPH_M.VSSX", "semantic": "网络链路", "line": "实线", "arrow": "无", "direction": "备选"},
        ],
        "layout": {
            "direction": "free",
            "spacing_h": 2.0,
            "spacing_v": 2.0,
            "notes": [
                "核心设备（路由器/交换机）居中",
                "终端设备围绕核心设备分布",
                "Cloud 图标表示外部网络，放在上方或边缘",
                "在连接线上标注带宽/协议",
            ],
        },
        "example": {
            "description": "办公网络：Internet(Cloud) → Firewall → Switch → Server/PC",
            "shapes": [
                {"id": "cloud", "type": "drop", "master_name": "Cloud", "stencil_name": "NETLOC_M.VSSX", "x": 4.25, "y": 9.5, "text": "Internet"},
                {"id": "fw", "type": "drop", "master_name": "Firewall", "stencil_name": "PERIPH_M.VSSX", "x": 4.25, "y": 7.5, "text": "Firewall"},
                {"id": "sw", "type": "drop", "master_name": "Switch", "stencil_name": "PERIPH_M.VSSX", "x": 4.25, "y": 5.5, "text": "Core Switch"},
                {"id": "srv1", "type": "drop", "master_name": "Server", "stencil_name": "PERIPH_M.VSSX", "x": 2, "y": 3.5, "text": "Web Server"},
                {"id": "srv2", "type": "drop", "master_name": "Server", "stencil_name": "PERIPH_M.VSSX", "x": 4.25, "y": 3.5, "text": "DB Server"},
                {"id": "pc", "type": "drop", "master_name": "User", "stencil_name": "PERIPH_M.VSSX", "x": 6.5, "y": 3.5, "text": "Workstation"},
            ],
            "connections": [
                {"from": "cloud", "to": "fw"},
                {"from": "fw", "to": "sw"},
                {"from": "sw", "to": "srv1"},
                {"from": "sw", "to": "srv2"},
                {"from": "sw", "to": "pc"},
            ],
            "notes": "网络图使用 AutoConnect。Cloud 来自 NETLOC_M.VSSX，其他设备来自 PERIPH_M.VSSX。注意不同 stencil 的形状需指明 stencil_name。",
        },
    },

    # ═══════════════════════════════════════════════════════════════
    # Cloud Architecture
    # ═══════════════════════════════════════════════════════════════
    "azure_architecture": {
        "name": "云架构图 — Azure",
        "name_en": "Azure Architecture Diagram",
        "standard": "Microsoft Azure 图标体系",
        "template": "AZUREDIAGRAMS_M.VSTX",
        "stencils": [
            {"file": "AZURECOMPUTE_M.VSSX", "purpose": "计算 (VM, App Service, K8s 等)"},
            {"file": "AZURENETWORKING_M.VSSX", "purpose": "网络 (VNet, LB, DNS 等)"},
            {"file": "AZURESTORAGE_M.VSSX", "purpose": "存储"},
            {"file": "AZUREDATABASES_M.VSSX", "purpose": "数据库"},
            {"file": "AZURESECURITY_M.VSSX", "purpose": "安全"},
            {"file": "AZUREIDENTITY_M.VSSX", "purpose": "身份认证"},
            {"file": "AZUREIOT_M.VSSX", "purpose": "IoT"},
            {"file": "AZUREINTEGRATION_M.VSSX", "purpose": "集成服务"},
            {"file": "AZUREAPPSERVICES_M.VSSX", "purpose": "应用服务"},
            {"file": "AZURECONTAINERS_M.VSSX", "purpose": "容器"},
            {"file": "AZUREDEVOPS_M.VSSX", "purpose": "DevOps"},
            {"file": "AZUREAIMACHINELEARNING_M.VSSX", "purpose": "AI/机器学习"},
            {"file": "AZUREANALYTICS_M.VSSX", "purpose": "分析"},
            {"file": "AZUREMONITOR_M.VSSX", "purpose": "监控"},
            {"file": "AZUREMANAGEMENTGOVERNANCE_M.VSSX", "purpose": "管理与治理"},
            {"file": "AZUREGENERAL_M.VSSX", "purpose": "通用符号"},
            {"file": "AZUREGENERALSYMBOLS_M.VSSX", "purpose": "通用标记"},
            {"file": "AZUREWEB_M.VSSX", "purpose": "Web 服务"},
        ],
        "shapes": [
            {"master": "Virtual Machine", "purpose": "虚拟机", "note": "AZURECOMPUTE_M.VSSX"},
            {"master": "App Services", "purpose": "应用服务", "note": "AZURECOMPUTE_M.VSSX"},
            {"master": "Function Apps", "purpose": "函数应用", "note": "AZURECOMPUTE_M.VSSX"},
            {"master": "Kubernetes Services", "purpose": "K8s 服务", "note": "AZURECOMPUTE_M.VSSX"},
            {"master": "Virtual Networks", "purpose": "虚拟网络", "note": "AZURENETWORKING_M.VSSX"},
            {"master": "Load Balancers", "purpose": "负载均衡器", "note": "AZURENETWORKING_M.VSSX"},
            {"master": "DNS Zones", "purpose": "DNS 区域", "note": "AZURENETWORKING_M.VSSX"},
        ],
        "edges": [
            {"master": "AutoConnect", "stencil": "", "semantic": "数据流/网络连接", "line": "实线", "arrow": "箭头", "direction": ""},
        ],
        "layout": {
            "direction": "top-to-bottom",
            "spacing_h": 1.5,
            "spacing_v": 1.5,
            "notes": [
                "分层布局（前端/应用/数据）",
                "使用矩形框表示 Resource Group / VNet / Subnet",
                "图标大小推荐 0.5 x 0.5 英寸",
            ],
        },
        "example": {
            "description": "Azure Web 应用：Front Door → App Service → SQL Database",
            "shapes": [
                {"id": "fd", "type": "drop", "master_name": "Front Doors", "stencil_name": "AZURENETWORKING_M.VSSX", "x": 4.25, "y": 9, "text": "Front Door"},
                {"id": "app", "type": "drop", "master_name": "App Services", "stencil_name": "AZURECOMPUTE_M.VSSX", "x": 4.25, "y": 7, "text": "App Service"},
                {"id": "sql", "type": "drop", "master_name": "SQL Databases", "stencil_name": "AZUREDATABASES_M.VSSX", "x": 4.25, "y": 5, "text": "SQL Database"},
                {"id": "blob", "type": "drop", "master_name": "Blob Storage", "stencil_name": "AZURESTORAGE_M.VSSX", "x": 6.5, "y": 7, "text": "Blob Storage"},
            ],
            "connections": [
                {"from": "fd", "to": "app"},
                {"from": "app", "to": "sql"},
                {"from": "app", "to": "blob"},
            ],
            "notes": "Azure 架构图使用 AutoConnect。不同类别的图标来自不同 stencil，需注意指定正确的 stencil_name。使用 list_masters() 查询可用 master 名称。",
        },
    },
    "aws_architecture": {
        "name": "云架构图 — AWS",
        "name_en": "AWS Architecture Diagram",
        "standard": "Amazon Web Services 架构图标标准",
        "template": "AWSDIAGRAMS_M.VSTX",
        "stencils": [
            {"file": "AWSCOMPUTE_M.VSSX", "purpose": "计算 (EC2, Lambda 等)"},
            {"file": "AWSDB_M.VSSX", "purpose": "数据库 (RDS, DynamoDB 等)"},
            {"file": "AWSNETCONTENTDELIVERY_M.VSSX", "purpose": "网络与内容分发 (VPC, CloudFront 等)"},
            {"file": "AWSSTORAGE_M.VSSX", "purpose": "存储 (S3, EBS 等)"},
            {"file": "AWSSECURITYCOMPLIANCE_M.VSSX", "purpose": "安全与合规 (IAM, WAF 等)"},
            {"file": "AWSANALYTICS_M.VSSX", "purpose": "分析"},
            {"file": "AWSIOT_M.VSSX", "purpose": "IoT"},
            {"file": "AWSML_M.VSSX", "purpose": "机器学习"},
            {"file": "AWSCONTAINERS_M.VSSX", "purpose": "容器 (ECS, EKS 等)"},
            {"file": "AWSDEVTOOLS_M.VSSX", "purpose": "开发工具"},
            {"file": "AWSAPPINT_M.VSSX", "purpose": "应用集成 (SQS, SNS 等)"},
            {"file": "AWSMGMTGOV_M.VSSX", "purpose": "管理与治理"},
            {"file": "AWSGEN_M.VSSX", "purpose": "通用符号"},
        ],
        "shapes": [],
        "edges": [
            {"master": "AutoConnect", "stencil": "", "semantic": "数据流/网络连接", "line": "实线", "arrow": "箭头", "direction": ""},
        ],
        "layout": {
            "direction": "top-to-bottom",
            "spacing_h": 1.5,
            "spacing_v": 1.5,
            "notes": [
                "分层布局",
                "使用矩形框表示 Region / VPC / Subnet / AZ",
                "图标大小推荐 0.5 x 0.5 英寸",
            ],
        },
        "example": {
            "description": "AWS Serverless：API Gateway → Lambda → DynamoDB + S3",
            "shapes": [
                {"id": "apigw", "type": "drop", "master_name": "Amazon API Gateway", "stencil_name": "AWSNETCONTENTDELIVERY_M.VSSX", "x": 4.25, "y": 9, "text": "API Gateway"},
                {"id": "lambda", "type": "drop", "master_name": "AWS Lambda", "stencil_name": "AWSCOMPUTE_M.VSSX", "x": 4.25, "y": 7, "text": "Lambda"},
                {"id": "dynamo", "type": "drop", "master_name": "Amazon DynamoDB", "stencil_name": "AWSDB_M.VSSX", "x": 2.5, "y": 5, "text": "DynamoDB"},
                {"id": "s3", "type": "drop", "master_name": "Bucket", "stencil_name": "AWSSTORAGE_M.VSSX", "x": 6, "y": 5, "text": "S3 Bucket"},
            ],
            "connections": [
                {"from": "apigw", "to": "lambda"},
                {"from": "lambda", "to": "dynamo"},
                {"from": "lambda", "to": "s3"},
            ],
            "notes": "AWS 架构图使用 AutoConnect。AWS master 名称通常以 'Amazon' 或 'AWS' 前缀开头，使用 list_masters() 确认精确名称。",
        },
    },
    "kubernetes": {
        "name": "Kubernetes 架构图",
        "name_en": "Kubernetes Architecture Diagram",
        "standard": "Kubernetes / CNCF 图标体系",
        "template": "AZUREDIAGRAMS_M.VSTX",
        "stencils": [
            {"file": "KUBERNETESVISIOSTENCIL_M.VSSX", "purpose": "Kubernetes 全部图标"},
        ],
        "shapes": [
            {"master": "pod", "purpose": "Pod", "note": ""},
            {"master": "deploy", "purpose": "Deployment", "note": ""},
            {"master": "rs", "purpose": "ReplicaSet", "note": ""},
            {"master": "ds", "purpose": "DaemonSet", "note": ""},
            {"master": "sts", "purpose": "StatefulSet", "note": ""},
            {"master": "job", "purpose": "Job", "note": ""},
            {"master": "cronjob", "purpose": "CronJob", "note": ""},
            {"master": "svc", "purpose": "Service", "note": ""},
            {"master": "ing", "purpose": "Ingress", "note": ""},
            {"master": "ep", "purpose": "Endpoint", "note": ""},
            {"master": "node", "purpose": "Node", "note": ""},
            {"master": "ns", "purpose": "Namespace", "note": ""},
            {"master": "pv", "purpose": "PersistentVolume", "note": ""},
            {"master": "pvc", "purpose": "PersistentVolumeClaim", "note": ""},
            {"master": "sc", "purpose": "StorageClass", "note": ""},
            {"master": "secret", "purpose": "Secret", "note": ""},
            {"master": "cm", "purpose": "ConfigMap", "note": ""},
            {"master": "sa", "purpose": "ServiceAccount", "note": ""},
            {"master": "hpa", "purpose": "HorizontalPodAutoscaler", "note": ""},
            {"master": "netpol", "purpose": "NetworkPolicy", "note": ""},
            {"master": "control-plane", "purpose": "Control Plane", "note": ""},
            {"master": "api", "purpose": "API Server", "note": ""},
            {"master": "etcd", "purpose": "etcd", "note": ""},
            {"master": "sched", "purpose": "Scheduler", "note": ""},
            {"master": "kubelet", "purpose": "kubelet", "note": ""},
            {"master": "k-proxy", "purpose": "kube-proxy", "note": ""},
        ],
        "edges": [
            {"master": "AutoConnect", "stencil": "", "semantic": "组件间关系", "line": "实线", "arrow": "箭头", "direction": ""},
        ],
        "layout": {
            "direction": "top-to-bottom",
            "spacing_h": 2.0,
            "spacing_v": 2.0,
            "notes": [
                "层级嵌套：Cluster > Node > Namespace > Deployment > Pod",
                "Control Plane 放在图表上方或左侧",
                "Worker Node 并排放在下方",
                "使用矩形框表示 Namespace 和 Node 边界",
            ],
        },
        "example": {
            "description": "K8s 应用部署：Ingress → Service → Deployment → Pod，含 ConfigMap",
            "shapes": [
                {"id": "ing", "type": "drop", "master_name": "ing", "stencil_name": "KUBERNETESVISIOSTENCIL_M.VSSX", "x": 4.25, "y": 9, "text": "Ingress"},
                {"id": "svc", "type": "drop", "master_name": "svc", "stencil_name": "KUBERNETESVISIOSTENCIL_M.VSSX", "x": 4.25, "y": 7, "text": "Service"},
                {"id": "deploy", "type": "drop", "master_name": "deploy", "stencil_name": "KUBERNETESVISIOSTENCIL_M.VSSX", "x": 4.25, "y": 5, "text": "Deployment"},
                {"id": "pod1", "type": "drop", "master_name": "pod", "stencil_name": "KUBERNETESVISIOSTENCIL_M.VSSX", "x": 2.5, "y": 3, "text": "Pod-1"},
                {"id": "pod2", "type": "drop", "master_name": "pod", "stencil_name": "KUBERNETESVISIOSTENCIL_M.VSSX", "x": 6, "y": 3, "text": "Pod-2"},
                {"id": "cm", "type": "drop", "master_name": "cm", "stencil_name": "KUBERNETESVISIOSTENCIL_M.VSSX", "x": 7, "y": 5, "text": "ConfigMap"},
            ],
            "connections": [
                {"from": "ing", "to": "svc"},
                {"from": "svc", "to": "deploy"},
                {"from": "deploy", "to": "pod1"},
                {"from": "deploy", "to": "pod2"},
                {"from": "cm", "to": "deploy"},
            ],
            "notes": "K8s 图的 master 名称是小写缩写（pod, deploy, svc, ing 等），与 kubectl 缩写一致。使用 AutoConnect。",
        },
    },

    # ═══════════════════════════════════════════════════════════════
    # Organization
    # ═══════════════════════════════════════════════════════════════
    "org_chart": {
        "name": "组织结构图",
        "name_en": "Organization Chart",
        "standard": "无统一国际标准（企业内部规范为主）",
        "template": "ORGCH_M.VSTX",
        "stencils": [
            {"file": "ORGCH_M.VSSX", "purpose": "完整组织结构图（推荐）"},
            {"file": "BASICORGCHART_M.VSSX", "purpose": "简化版"},
        ],
        "shapes": [
            {"master": "Executive", "purpose": "高管", "note": "最高层级"},
            {"master": "Manager", "purpose": "经理", "note": "中层管理"},
            {"master": "Position", "purpose": "职位", "note": "普通岗位"},
            {"master": "Consultant", "purpose": "顾问", "note": "外部/临时角色"},
            {"master": "Vacancy", "purpose": "空缺", "note": "待招聘岗位"},
            {"master": "Assistant", "purpose": "助理", "note": "侧挂在管理者旁"},
            {"master": "Staff", "purpose": "员工", "note": "基层"},
            {"master": "Team frame", "purpose": "团队框", "note": "分组容器"},
            {"master": "Multiple shapes", "purpose": "多个职位", "note": "批量表示"},
            {"master": "Three positions", "purpose": "三个职位", "note": "紧凑表示"},
            {"master": "Title/Date", "purpose": "标题/日期", "note": "图表标题"},
            {"master": "Title", "purpose": "标题", "note": ""},
        ],
        "edges": [
            {"master": "Dynamic connector", "stencil": "ORGCH_M.VSSX", "semantic": "直属汇报", "line": "实线", "arrow": "无", "direction": ""},
            {"master": "Dotted-line report", "stencil": "ORGCH_M.VSSX", "semantic": "虚线汇报", "line": "虚线", "arrow": "无", "direction": "矩阵管理关系"},
            {"master": "AutoConnect", "stencil": "", "semantic": "层级连接", "line": "实线", "arrow": "无", "direction": "默认"},
        ],
        "layout": {
            "direction": "top-to-bottom",
            "spacing_h": 1.5,
            "spacing_v": 1.0,
            "notes": [
                "同级别水平对齐",
                "Assistant 偏移挂在管理者侧面",
            ],
        },
        "example": {
            "description": "公司组织结构：CEO → VP Engineering / VP Sales → Managers → Staff",
            "shapes": [
                {"id": "ceo", "type": "drop", "master_name": "Executive", "stencil_name": "ORGCH_M.VSSX", "x": 4.25, "y": 9.5, "text": "CEO\nJohn Smith"},
                {"id": "vpe", "type": "drop", "master_name": "Manager", "stencil_name": "ORGCH_M.VSSX", "x": 2.5, "y": 7.5, "text": "VP Engineering\nJane Doe"},
                {"id": "vps", "type": "drop", "master_name": "Manager", "stencil_name": "ORGCH_M.VSSX", "x": 6, "y": 7.5, "text": "VP Sales\nBob Lee"},
                {"id": "dev1", "type": "drop", "master_name": "Position", "stencil_name": "ORGCH_M.VSSX", "x": 1.5, "y": 5.5, "text": "Dev Manager\nAlice"},
                {"id": "dev2", "type": "drop", "master_name": "Position", "stencil_name": "ORGCH_M.VSSX", "x": 3.5, "y": 5.5, "text": "QA Manager\nCharlie"},
                {"id": "sales1", "type": "drop", "master_name": "Position", "stencil_name": "ORGCH_M.VSSX", "x": 6, "y": 5.5, "text": "Sales Rep\nDave"},
            ],
            "connections": [
                {"from": "ceo", "to": "vpe"},
                {"from": "ceo", "to": "vps"},
                {"from": "vpe", "to": "dev1"},
                {"from": "vpe", "to": "dev2"},
                {"from": "vps", "to": "sales1"},
            ],
            "notes": "组织结构图使用 AutoConnect 或 Dynamic connector。Executive 用于最高层，Manager 用于中层，Position 用于普通岗位。",
        },
    },

    # ═══════════════════════════════════════════════════════════════
    # Data Flow
    # ═══════════════════════════════════════════════════════════════
    "data_flow_diagram": {
        "name": "数据流图",
        "name_en": "Data Flow Diagram",
        "standard": "Yourdon-DeMarco / Gane-Sarson",
        "template": "DATFLO_M.VSTX",
        "stencils": [
            {"file": "DATFLO_M.VSSX", "purpose": "数据流图全部形状"},
        ],
        "shapes": [
            {"master": "Data process", "purpose": "数据处理", "note": "圆形"},
            {"master": "External interactor", "purpose": "外部实体", "note": "矩形"},
            {"master": "Data store", "purpose": "数据存储", "note": "开放端矩形"},
            {"master": "Object", "purpose": "对象", "note": "通用对象"},
            {"master": "Multiple process", "purpose": "多重处理", "note": ""},
            {"master": "Oval process", "purpose": "椭圆处理", "note": ""},
        ],
        "edges": [
            {"master": "Center to center 1", "stencil": "DATFLO_M.VSSX", "semantic": "数据流", "line": "实线", "arrow": "箭头", "direction": ""},
            {"master": "Center to center 2", "stencil": "DATFLO_M.VSSX", "semantic": "数据流（备选）", "line": "实线", "arrow": "箭头", "direction": ""},
            {"master": "Dynamic connector", "stencil": "DATFLO_M.VSSX", "semantic": "通用连接", "line": "实线", "arrow": "箭头", "direction": ""},
            {"master": "AutoConnect", "stencil": "", "semantic": "数据流", "line": "实线", "arrow": "箭头", "direction": "默认"},
        ],
        "layout": {
            "direction": "free",
            "spacing_h": 2.5,
            "spacing_v": 2.0,
            "notes": [
                "外部实体放在图表边缘",
                "数据存储放在右侧或底部",
                "分层：Context Diagram (Level 0) → Level 1 → Level 2",
            ],
        },
        "example": {
            "description": "客户订单系统 (Level 0)：Customer → Order Process → Inventory Store",
            "shapes": [
                {"id": "customer", "type": "drop", "master_name": "External interactor", "stencil_name": "DATFLO_M.VSSX", "x": 1.5, "y": 7, "text": "Customer"},
                {"id": "process", "type": "drop", "master_name": "Data process", "stencil_name": "DATFLO_M.VSSX", "x": 4.25, "y": 7, "text": "1.0\nProcess Order"},
                {"id": "store", "type": "drop", "master_name": "Data store", "stencil_name": "DATFLO_M.VSSX", "x": 7, "y": 7, "text": "D1 Inventory"},
                {"id": "supplier", "type": "drop", "master_name": "External interactor", "stencil_name": "DATFLO_M.VSSX", "x": 4.25, "y": 4, "text": "Supplier"},
            ],
            "connections": [
                {"from": "customer", "to": "process", "connector_master": "Center to center 1", "connector_stencil": "DATFLO_M.VSSX"},
                {"from": "process", "to": "store", "connector_master": "Center to center 1", "connector_stencil": "DATFLO_M.VSSX"},
                {"from": "process", "to": "supplier", "connector_master": "Center to center 1", "connector_stencil": "DATFLO_M.VSSX"},
            ],
            "notes": "数据流图推荐使用 'Center to center 1' 连接器。External interactor 放在边缘，Data process 居中。",
        },
    },

    # ═══════════════════════════════════════════════════════════════
    # Quality & Lean
    # ═══════════════════════════════════════════════════════════════
    "cause_and_effect": {
        "name": "因果图 / 鱼骨图",
        "name_en": "Cause and Effect / Fishbone Diagram",
        "standard": "石川馨 (Kaoru Ishikawa) 因果分析法",
        "template": "CAUSEF_M.VSTX",
        "stencils": [
            {"file": "CAUSEF_M.VSSX", "purpose": "因果图形状"},
        ],
        "shapes": [],
        "edges": [],
        "layout": {
            "direction": "right-to-left",
            "spacing_h": 2.0,
            "spacing_v": 1.5,
            "notes": [
                "鱼头（效果/问题）在右侧",
                "水平主线为主骨架",
                "主因分支从主线斜向上/下分出",
                "子因分支从主因分支进一步细分",
                "常用 6M 分类：Man, Machine, Material, Method, Measurement, Mother Nature",
                "使用 list_masters('CAUSEF_M.VSSX') 获取具体 Master 名称",
            ],
        },
        "example": {
            "description": "制造缺陷鱼骨图：Effect + Category 1/2 + Primary/Secondary causes",
            "shapes": [
                {"id": "effect", "type": "drop", "master_name": "Effect", "stencil_name": "CAUSEF_M.VSSX", "x": 7, "y": 5.5, "text": "Product Defect"},
                {"id": "cat1", "type": "drop", "master_name": "Category 1", "stencil_name": "CAUSEF_M.VSSX", "x": 3, "y": 8, "text": "Man"},
                {"id": "cat2", "type": "drop", "master_name": "Category 2", "stencil_name": "CAUSEF_M.VSSX", "x": 3, "y": 3, "text": "Machine"},
                {"id": "p1", "type": "drop", "master_name": "Primary cause 1", "stencil_name": "CAUSEF_M.VSSX", "x": 2, "y": 9, "text": "Lack of Training"},
                {"id": "p2", "type": "drop", "master_name": "Primary cause 1", "stencil_name": "CAUSEF_M.VSSX", "x": 2, "y": 2, "text": "Worn Parts"},
                {"id": "s1", "type": "drop", "master_name": "Secondary cause 1", "stencil_name": "CAUSEF_M.VSSX", "x": 1, "y": 9.5, "text": "No Manual"},
            ],
            "connections": [
                {"from": "cat1", "to": "effect"},
                {"from": "cat2", "to": "effect"},
                {"from": "p1", "to": "cat1"},
                {"from": "p2", "to": "cat2"},
                {"from": "s1", "to": "p1"},
            ],
            "notes": "因果图使用 AutoConnect。Effect 在右侧，Category 在中间斜向分支，Primary/Secondary cause 在分支末端。Master 名称为 Effect, Category 1/2, Primary cause 1/2, Secondary cause 1-6。",
        },
    },
    "value_stream_mapping": {
        "name": "值流图",
        "name_en": "Value Stream Mapping",
        "standard": "精益制造 (Lean Manufacturing) / 丰田生产系统",
        "template": "VSM_M.VSTX",
        "stencils": [
            {"file": "VSM_M.VSSX", "purpose": "值流图形状"},
        ],
        "shapes": [],
        "edges": [],
        "layout": {
            "direction": "left-to-right",
            "spacing_h": 2.0,
            "spacing_v": 2.0,
            "notes": [
                "物料流在下方，实线箭头",
                "信息流在上方，虚线箭头/闪电线",
                "时间线在底部，记录 CT/LT",
                "使用 list_masters('VSM_M.VSSX') 获取具体 Master 名称",
            ],
        },
        "example": {
            "description": "简单生产线 VSM：Supplier → Process 1 → Process 2 → Customer，含库存和时间线",
            "shapes": [
                {"id": "supplier", "type": "drop", "master_name": "Customer/Supplier", "stencil_name": "VSM_M.VSSX", "x": 1, "y": 8, "text": "Supplier"},
                {"id": "proc1", "type": "drop", "master_name": "Process", "stencil_name": "VSM_M.VSSX", "x": 3.5, "y": 5.5, "text": "Stamping\nCT=10s"},
                {"id": "inv1", "type": "drop", "master_name": "Inventory", "stencil_name": "VSM_M.VSSX", "x": 5.5, "y": 5.5, "text": "500 pcs"},
                {"id": "proc2", "type": "drop", "master_name": "Process", "stencil_name": "VSM_M.VSSX", "x": 7.5, "y": 5.5, "text": "Assembly\nCT=30s"},
                {"id": "customer", "type": "drop", "master_name": "Customer/Supplier", "stencil_name": "VSM_M.VSSX", "x": 9.5, "y": 8, "text": "Customer"},
                {"id": "ctrl", "type": "drop", "master_name": "Production control", "stencil_name": "VSM_M.VSSX", "x": 5, "y": 9.5, "text": "Production\nControl"},
                {"id": "tl1", "type": "drop", "master_name": "Timeline segment", "stencil_name": "VSM_M.VSSX", "x": 3.5, "y": 2, "text": "5 days"},
                {"id": "tl2", "type": "drop", "master_name": "Timeline segment", "stencil_name": "VSM_M.VSSX", "x": 7.5, "y": 2, "text": "2 days"},
            ],
            "connections": [
                {"from": "supplier", "to": "proc1"},
                {"from": "proc1", "to": "inv1"},
                {"from": "inv1", "to": "proc2"},
                {"from": "proc2", "to": "customer"},
            ],
            "notes": "VSM 使用 AutoConnect。Master 名称：Customer/Supplier, Process, Inventory, Push arrow, Shipment truck, Production control, Electronic information, Timeline segment/total, Data table。",
        },
    },
    "epc": {
        "name": "事件驱动过程链",
        "name_en": "Event-driven Process Chain",
        "standard": "ARIS 方法论 (Prof. Scheer) / SAP",
        "template": "EPC_M.VSTX",
        "stencils": [
            {"file": "EPC_M.VSSX", "purpose": "EPC 图形状"},
        ],
        "shapes": [],
        "edges": [],
        "layout": {
            "direction": "top-to-bottom",
            "spacing_h": 2.0,
            "spacing_v": 1.0,
            "notes": [
                "事件（六边形）与功能（圆角矩形）交替排列",
                "逻辑连接：AND/OR/XOR 操作符",
                "使用 list_masters('EPC_M.VSSX') 获取具体 Master 名称",
            ],
        },
        "example": {
            "description": "采购申请 EPC：Event → Function → XOR → Event/Event 交替链",
            "shapes": [
                {"id": "e1", "type": "drop", "master_name": "Event", "stencil_name": "EPC_M.VSSX", "x": 4.25, "y": 10, "text": "Purchase\nRequired"},
                {"id": "f1", "type": "drop", "master_name": "Function", "stencil_name": "EPC_M.VSSX", "x": 4.25, "y": 8.5, "text": "Create Purchase\nRequisition"},
                {"id": "e2", "type": "drop", "master_name": "Event", "stencil_name": "EPC_M.VSSX", "x": 4.25, "y": 7, "text": "Requisition\nCreated"},
                {"id": "f2", "type": "drop", "master_name": "Function", "stencil_name": "EPC_M.VSSX", "x": 4.25, "y": 5.5, "text": "Approve\nRequisition"},
                {"id": "xor", "type": "drop", "master_name": "XOR", "stencil_name": "EPC_M.VSSX", "x": 4.25, "y": 4},
                {"id": "e3", "type": "drop", "master_name": "Event", "stencil_name": "EPC_M.VSSX", "x": 2.5, "y": 2.5, "text": "Approved"},
                {"id": "e4", "type": "drop", "master_name": "Event", "stencil_name": "EPC_M.VSSX", "x": 6, "y": 2.5, "text": "Rejected"},
                {"id": "org", "type": "drop", "master_name": "Organizational unit", "stencil_name": "EPC_M.VSSX", "x": 7, "y": 5.5, "text": "Purchasing\nDept"},
            ],
            "connections": [
                {"from": "e1", "to": "f1"},
                {"from": "f1", "to": "e2"},
                {"from": "e2", "to": "f2"},
                {"from": "f2", "to": "xor"},
                {"from": "xor", "to": "e3"},
                {"from": "xor", "to": "e4"},
                {"from": "org", "to": "f2"},
            ],
            "notes": "EPC 使用 AutoConnect。核心规则：事件(Event)和功能(Function)严格交替排列。逻辑操作符有 XOR, OR, AND。Organizational unit 侧挂在 Function 旁边。",
        },
    },

    # ═══════════════════════════════════════════════════════════════
    # Block Diagram
    # ═══════════════════════════════════════════════════════════════
    "block_diagram": {
        "name": "块图",
        "name_en": "Block Diagram",
        "standard": "通用系统描述 / 概念性架构表达",
        "template": "BLOCK_M.VSTX",
        "stencils": [
            {"file": "BLOCK_M.VSSX", "purpose": "基本块图（推荐）"},
            {"file": "BLOCK3_M.VSSX", "purpose": "3D 块图"},
            {"file": "BLOCKP_M.VSSX", "purpose": "透视块图"},
        ],
        "shapes": [
            {"master": "Box", "purpose": "块/框", "note": "基本矩形"},
            {"master": "Circle", "purpose": "圆形", "note": ""},
            {"master": "Diamond", "purpose": "菱形", "note": ""},
            {"master": "Arrow box", "purpose": "箭头框", "note": "单向"},
            {"master": "Double Arrow Box", "purpose": "双箭头框", "note": "双向"},
            {"master": "Quad Arrow Box", "purpose": "四向箭头框", "note": ""},
            {"master": "Auto-height box", "purpose": "自动高度框", "note": "文本越多越高"},
            {"master": "Auto-size box", "purpose": "自动大小框", "note": ""},
            {"master": "3-D box", "purpose": "3D 框", "note": ""},
            {"master": "3-D Circle", "purpose": "3D 圆形", "note": ""},
            {"master": "Layered Box", "purpose": "分层框", "note": "表示多实例/栈"},
            {"master": "Concentric layer 1", "purpose": "同心圆第 1 层", "note": "洋葱圈模型"},
            {"master": "Concentric layer 2", "purpose": "同心圆第 2 层", "note": ""},
            {"master": "Concentric layer 3", "purpose": "同心圆第 3 层", "note": ""},
            {"master": "Concentric center", "purpose": "同心圆中心", "note": ""},
            {"master": "Partial layer 1", "purpose": "扇环第 1 层", "note": "饼图式分区"},
            {"master": "Partial layer 2", "purpose": "扇环第 2 层", "note": ""},
            {"master": "Partial layer 3", "purpose": "扇环第 3 层", "note": ""},
            {"master": "Partial layer 4", "purpose": "扇环第 4 层", "note": ""},
        ],
        "edges": [
            {"master": "Dynamic connector", "stencil": "BLOCK_M.VSSX", "semantic": "动态连接线", "line": "实线", "arrow": "箭头", "direction": ""},
            {"master": "Line-curve connector", "stencil": "BLOCK_M.VSSX", "semantic": "直线-曲线连接", "line": "实线", "arrow": "箭头", "direction": ""},
            {"master": "Dotted line", "stencil": "BLOCK_M.VSSX", "semantic": "虚线", "line": "虚线", "arrow": "无", "direction": ""},
            {"master": "Mid-arrow", "stencil": "BLOCK_M.VSSX", "semantic": "中间箭头线", "line": "实线", "arrow": "中间箭头", "direction": ""},
            {"master": "Arced arrow", "stencil": "BLOCK_M.VSSX", "semantic": "弧形箭头", "line": "弧线", "arrow": "箭头", "direction": ""},
            {"master": "Single arrowhead", "stencil": "BLOCK_M.VSSX", "semantic": "单箭头", "line": "实线", "arrow": "箭头", "direction": ""},
            {"master": "Double arrowhead", "stencil": "BLOCK_M.VSSX", "semantic": "双箭头", "line": "实线", "arrow": "双箭头", "direction": ""},
            {"master": "1-D single", "stencil": "BLOCK_M.VSSX", "semantic": "一维单向", "line": "实线", "arrow": "箭头", "direction": ""},
            {"master": "1-D double", "stencil": "BLOCK_M.VSSX", "semantic": "一维双向", "line": "实线", "arrow": "双箭头", "direction": ""},
            {"master": "2-D single", "stencil": "BLOCK_M.VSSX", "semantic": "二维单向", "line": "实线", "arrow": "箭头", "direction": ""},
            {"master": "2-D double", "stencil": "BLOCK_M.VSSX", "semantic": "二维双向", "line": "实线", "arrow": "双箭头", "direction": ""},
            {"master": "Curved arrow", "stencil": "BLOCK_M.VSSX", "semantic": "曲线箭头", "line": "曲线", "arrow": "箭头", "direction": ""},
            {"master": "AutoConnect", "stencil": "", "semantic": "默认连接", "line": "实线", "arrow": "箭头", "direction": ""},
        ],
        "layout": {
            "direction": "free",
            "spacing_h": 1.5,
            "spacing_v": 1.5,
            "notes": [
                "常用从左到右或从上到下",
                "使用 Layered Box 或 Concentric 系列表达层次",
            ],
        },
        "example": {
            "description": "系统架构块图：Client → Load Balancer → App Server (x2) → Database",
            "shapes": [
                {"id": "client", "type": "drop", "master_name": "Box", "stencil_name": "BLOCK_M.VSSX", "x": 1.5, "y": 7, "text": "Client"},
                {"id": "lb", "type": "drop", "master_name": "Diamond", "stencil_name": "BLOCK_M.VSSX", "x": 4.25, "y": 7, "text": "Load\nBalancer"},
                {"id": "app1", "type": "drop", "master_name": "Box", "stencil_name": "BLOCK_M.VSSX", "x": 6.5, "y": 8.5, "text": "App Server 1"},
                {"id": "app2", "type": "drop", "master_name": "Box", "stencil_name": "BLOCK_M.VSSX", "x": 6.5, "y": 5.5, "text": "App Server 2"},
                {"id": "db", "type": "drop", "master_name": "3-D box", "stencil_name": "BLOCK_M.VSSX", "x": 9, "y": 7, "text": "Database"},
            ],
            "connections": [
                {"from": "client", "to": "lb"},
                {"from": "lb", "to": "app1"},
                {"from": "lb", "to": "app2"},
                {"from": "app1", "to": "db"},
                {"from": "app2", "to": "db"},
            ],
            "notes": "块图使用 AutoConnect 或 BLOCK_M.VSSX 内的连接器（Dynamic connector, 1-D single 等）。适合概念性架构表达，形状选择灵活。",
        },
    },
}


def list_types() -> list[dict]:
    """Return a summary list of all diagram types."""
    return [
        {
            "id": k,
            "name": v["name"],
            "name_en": v["name_en"],
            "standard": v["standard"],
            "template": v["template"],
        }
        for k, v in STANDARDS.items()
    ]


def get_standard(diagram_type: str) -> dict | None:
    """Return the full standard for a given diagram type, or None if not found."""
    return STANDARDS.get(diagram_type)
